### ISSUE TITLE
Example code within the demo

### ISSUE THREAD

**Issue by foucist** [ArthurClemens/polythene#64]
I know the demo is generated from the tests.  I was curious if it would be possible to include example source code next to each example in the demo. 

Something like this perhaps:  http://www.material-ui.com/#/components/app-bar

It didn't seem that trivial though because it looks like you're evaluating the code on the fly? Would have to build a separate "example code" generator?

**Comment by ArthurClemens** [comment]
The demo code reuses quite a lot of helper components and functions in order to reduce code duplication. To make all this code available as easy to understand / ready-to-use snippets, the demo code needs to be made simpler per example, creating duplicate code, and reduced in scope.

Instead I have opted to add many code examples in the docs, illustrated with live code examples at JSFiddle. Which has all the benefits of a playground: changing, forking, copying.
